force-app/main/default/objects/C3C_QueueProcessingAsyncControl2__c/C3C_QueueProcessingAsyncControl2__c.object-meta.xml
<CustomObject>
    <description>Objetivo: Ter um controle assíncrono para lote de processamento da fila, para que não sejam postas em execução 2 ou mais batches  do mesmo serviço</description>
    <label>Controle Assíncrono de Processamento</label>
    <nameField>
        <label>Nome</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Controle Assíncrono de Processamento</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/C3C_QueueProcessingAsyncControl2__c/fields/InExecution__c.field-meta.xml
<CustomField>
    <fullName>InExecution__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Inicialmente preenchido na classe C3C_QueueProcessingBatchService, no método executeAsyncQueueProcessingBatch. Ao iniciar a execução de um lote de processamento assíncrono da fila, é setado como true</description>
    <label>Está em execução</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/C3C_QueueProcessingAsyncControl2__c/fields/InExecutionQueueProcessingBatchId__c.field-meta.xml
<CustomField>
    <fullName>InExecutionQueueProcessingBatchId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lote em execução</label>
    <referenceTo>C3C_QueueProcessingBatch__c</referenceTo>
    <relationshipLabel>Controle Assíncrono de Processamento (Lote em execução)</relationshipLabel>
    <relationshipName>Controle_Ass_ncrono_de_Processamento</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/C3C_QueueProcessingAsyncControl2__c/fields/NextExecuteQueueProcessingBatchId__c.field-meta.xml
<CustomField>
    <fullName>NextExecuteQueueProcessingBatchId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Próximo lote que será executado</label>
    <referenceTo>C3C_QueueProcessingBatch__c</referenceTo>
    <relationshipLabel>Controle Assíncrono de Processamento</relationshipLabel>
    <relationshipName>C3C_QueueProcessingAsyncControl</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/C3C_QueueProcessingAsyncControl2__c/fields/ServiceName__c.field-meta.xml
<CustomField>
    <fullName>ServiceName__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>Nome do Serviço</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/C3C_QueueProcessingAsyncControl2Selector.cls
public with sharing class C3C_QueueProcessingAsyncControl2Selector implements C3C_IQProcessingAsyncControl2Selector
{
    private String getDefaultQuery()
    {
        return 'SELECT Id,'+ 
            'InExecution__c, ' +
            'ServiceName__c, ' +
            'InExecutionQueueProcessingBatchId__c, ' +
            'NextExecuteQueueProcessingBatchId__c ' +
            'FROM C3C_QueueProcessingAsyncControl2__c';
    }

    public Object selectByServiceNames(Set<String> serviceNames)
    {
        String query = getDefaultQuery();

        query += ' WHERE ServiceName__c IN :serviceNames';

        return Database.query(query);
    }

    public C3C_QueueProcessingAsyncControl2__c selectByServiceName(String serviceName)
    {
        String query = getDefaultQuery();

        query += ' WHERE ServiceName__c = :serviceName LIMIT 1';

        List<C3C_QueueProcessingAsyncControl2__c> queryResult = Database.query(query);

        if(!queryResult.isEmpty()) { return queryResult[0]; }

        return null;
    }
    @testVisible
    private static void testCoverage() {
        Integer i = 0;
        i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;
        
        i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;
    }
}